# Generated by Django 4.1.7 on 2023-03-23 14:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField()),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('detergent_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fabcon_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bleach_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('plastic_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.PositiveSmallIntegerField(choices=[(0, 'Unpaid'), (1, 'Cash'), (2, 'GCash')], default=1)),
                ('payment_made', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('date_required', models.DateTimeField(blank=True, null=True)),
                ('date_claimed', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.customer')),
            ],
        ),
    ]
